version: '3.3'
services:
#    api:
#      build:  .
#      container_name: user_api
#      hostname: api.users.dev
#      ports:
#        - 80
#        - 443
#      links:
#        - db
#      depends_on:
#        - db
    db:
      image: mariadb:10.4.10
      environment:
        MYSQL_ROOT_PASSWORD: admin2019
        MYSQL_USER: devDbUser
        MYSQL_PASSWORD: thisAmazingPassword
        MYSQL_DATABASE: api_dev
      ports:
        - 3306:3306

